---
title: "Dataset Characterization Notebook 1"
date: 2026-04-19
author: Andrei Akopian
---

Imports

In [2]:
import pandas as pd

In [4]:
import sys
from pathlib import Path

github_root = Path.cwd().resolve().parents[2]
sys.path.append(str(github_root))

In [24]:
DIAGNOSIS_RECORDS_TRAIN = "../../data/diagnosis_records_train.csv"
PARTICIPANT_DATA_TRAIN = "../../data/participant_data_train.csv"
WEARABLE_DATA_TRAIN = "../../data/wearable_data_train.csv"

Loading the Dataset

In [26]:
diagnosis_records_train = pd.read_csv(DIAGNOSIS_RECORDS_TRAIN)
participant_data_train = pd.read_csv(PARTICIPANT_DATA_TRAIN)
wearable_data_train = pd.read_csv(WEARABLE_DATA_TRAIN)

In [32]:
diagnosis_records_train

         ID HOSPITAL_CLINIC         HCP        date                  diagnosis
0       380     L_000130637  D_00612441  2022-04-26              Stomach Aches
1      1372     L_000758610  D_00910403  2019-03-16                        flu
2      4497     L_000649255  D_02265924  2020-03-17            Sinus infection
3       151     L_000041260  D_01926201  2025-03-26                influenza a
4      2185     L_000641795  D_01556668  2024-02-08                   diarrhea
...     ...             ...         ...         ...                        ...
11532  4375     L_000825198  D_02207707  2025-01-13                  INFLUENZA
11533  1091     L_000774357  D_00725720  2024-02-29                 Dermatitis
11534  6494     L_000911279  D_00466434  2019-05-20  Central Sleep Apnea (CSA)
11535  3731     L_000435370  D_02300982  2023-09-09                 BRONCHITIS
11536  1210     L_000839523  D_02627258  2018-06-17             Food poisoning

[11537 rows x 5 columns]

In [25]:
participant_data_train.shape

(20000, 26)

## Diagnosis

In [40]:
len(set(diagnosis_records_train["HCP"]))

11520

## Wearable Data

In [50]:
wearable_data_train

,ID,timestamp,day_of_week,snoring,n_wakeups,sleep_duration,sleep_light,sleep_deep,sleep_rem,afib_daily,...,hospital_state,household_size,altitude,os,app_version,battery_level,skin_temp,atmospheric_temp_lower,atmospheric_temp_upper,app_crash
0,4,2016-01-04,3,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CT,4,147,iOS 18,4.3.1,74,33.7,-4.0,4.1,0
1,4,2016-01-05,4,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CT,4,147,iOS 18,4.3.1,50,33.0,1.7,8.3,0
2,4,2016-01-07,6,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CT,4,147,iOS 18,4.3.1,31,33.1,-7.4,4.2,0
3,4,2016-01-08,7,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CT,4,147,iOS 18,4.3.1,15,33.1,-1.4,7.5,0
4,4,2016-01-10,2,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CT,4,147,iOS 18,4.3.1,48,33.1,1.0,10.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507859,19996,2016-12-06,4,NaN,NaN,NaN,NaN,NaN,NaN,0,...,MD,6,0,iOS 18,4.3.0,100,32.7,-5.4,5.1,0
507860,19996,2016-12-07,5,NaN,NaN,NaN,NaN,NaN,NaN,0,...,MD,6,0,iOS 18,4.3.0,82,32.3,6.0,13.0,0
507861,19996,2016-12-11,2,NaN,NaN,NaN,NaN,NaN,NaN,0,...,MD,6,0,iOS 18,4.3.0,82,33.0,6.3,16.1,0
507862,19996,2016-12-18,2,0.0,0.0,7.538841,5.972245,0.431076,1.135519,0,...,MD,6,0,iOS 18,4.3.0,5,32.3,-13.0,-4.0,0
507863,19996,2016-12-24,1,NaN,NaN,NaN,NaN,NaN,NaN,0,...,MD,6,0,iOS 18,4.3.0,82,32.4,-1.1,9.3,0

In [57]:
wearable_data_train["afib_daily"].value_counts()

afib_daily
0    497272
1     10592
Name: count, dtype: int64

In [58]:
wearable_data_train['app_version'].value_counts()

app_version
5.1.0    116968
5.0.0     94031
5.0.1     91207
4.4.0     64607
4.3.1     54645
4.3.0     37751
4.2.1     22779
4.2.0     17484
4.1.0      8392
Name: count, dtype: int64